### ISSUE TITLE
Progress callback called too frequently - clutters logfiles if logging within function

### ISSUE THREAD

**Issue by AddisonG** [jbardin/scp.py#144]
I know the progress logs are primarily for humans to read/watch. However, it is often useful to know how much of a file was uploaded (or how long it took) if it fails, so logging the progress to a file makes sense.

However, the progress is logged several times a second, creating thousands of logs for even very small files. Is there any way to reduce the frequency of the log messages? Putting a `sleep` in the callback only freezes the transfer.

**Comment by remram44** [comment]
scp.py does not log so I am not sure where your output could be from?

**Comment by AddisonG** [comment]
From the example in [your readme](https://github.com/jbardin/scp.py/blob/master/README.rst#tracking-progress-of-your-file-uploadsdownloads):

```
# Define progress callback that prints the current percentage completed for the file
def progress(filename, size, sent):
    sys.stdout.write("%s\'s progress: %.2f%%   \r" % (filename, float(sent)/float(size)*100) )
```

I'm using this to output log messages (to stdout), however this function is called too often.

**Comment by remram44** [comment]
This example uses `\r` to replace the current line. It's meant for a terminal, of course this won't work if you send that to a log file.

If you are directing this output to log, isn't it better to log the time it took, or the exception, after it's done? Otherwise you can always not print every single time the progress function is called. Either way I don't think a change is warranted to scp.py or the README.
