### ISSUE TITLE
Top-level functions

### ISSUE THREAD

**Issue by kimgr** [jbardin/scp.py#71]
I'd like to add two utility functions to the scp module -- get and put, something like;

```
def get(transport, remote_path, local_path='',
        recursive=False, preserve_times=False):
     return SCPClient(transport).get(...)
```

In many one-off use cases, creating an SCPClient object is more syntactic noise than necessary.

I'd be happy to work on patches if this sounds reasonable.

**Comment by remram44** [comment]
`SCPClient(transport).get(...)` is not that much more to write. I agree that this might make sense conceptually, but the truth is that SCPClient closes the channel after each `get()` or `put()` invocation so there is no real point in writing the proper `with SCPClient(...) as client: client.get(...)` instead of the chained `SCPClient(...).get(...)`.
